solution with beautiful design
hheight/bulls-and-cows pull request #1
Opened 2020-03-29 18:45 UTC by hheight

2020-03-30 15:47 UTC, denys-cheporniuk requested changes
добав трохи стилів, зроби гру яку цікаво грати)

2020-03-30 15:47 UTC, Denchepornyuk commented on src/scripts/main.js
> +    alertMsg.innerHTML = '';
використай switch

2020-04-07 16:06 UTC, vkryvytskyy commented
<img width="501" alt="image" src="https://user-images.githubusercontent.com/38065883/78692620-d776bd00-7902-11ea-99a4-dac88282a0e2.png">
Было бы здорово видеть число, за сколько попыток мне удалось)

2020-04-07 16:06 UTC, vkryvytskyy commented
А так все круто)

2020-05-28 09:33 UTC, merged